# Generated by Django 4.0.3 on 2022-05-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='icon',
            field=models.CharField(default='php', max_length=10),
            preserve_default=False,
        ),
    ]
