# Generated by Django 4.0.3 on 2022-05-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizcategory_options_quizcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
